# Generated by Django 4.2.7 on 2023-12-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
