# Generated by Django 4.2.7 on 2023-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
