# Generated by Django 4.2.6 on 2023-12-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
